#!/usr/bin/env bash
# install nginx and configures it

sudo apt update
sudo apt install -y nginx
sudo sed -i 's/^listen\s*80\s*;/listen 80;/g' /etc/nginx/sites-available/default
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
