#!/usr/bin/env bash
# Installs nginx on web server, /redirect_me is redirecting to another page.

apt-get update
apt-get install -y nginx
echo "Hello World!!!" > /etc/nginx/html/index.html
cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;

    location /redirect_me {
        return 301 https://google.com;
    }
}
EOF
service nginx restart
