#!/usr/bin/env bash
#display "bad luck" for the 4th, "good luck" for the 8th and Best School other loop iterations.
i=0
while [ $i -ne 10 ]
do 
    if [ "$i" -eq 3 ]; then echo "bad luck"; 
    elif [ "$i" -eq 7 ]; then echo "good luck";
    else echo "Best School"; fi 
    (( i += 1 ))
done