#!/usr/bin/env bash
#display "bad luck" for the 4th, "good luck" for the 8th and Best School other loop iterations.
i=1
while [ $i -le 20 ]
do 
    echo $i
    case $i in
        (4) echo "bad luck from China";;
        (9) echo "bad luck from Japan";;
        (17) echo "bad luck from Italy";;
    esac
    (( i+=1))
done