#!/usr/bin/env bash
#display Best School 10 times
i=0
j=1
while [ $i -le 12 ]
do 
    echo "Hour: "$i
    while [ $j -le 59 ]
    do 
        echo $j 
        (( j+=1 )) 
    done
    (( i+=1))
    (( j=1 )) 
done