#!/usr/bin/env bash
#configures the container, iorder for nginx to be listening on all active IPs on port 8080, and running as nginx user.
chmod 644 /etc/nginx/nginx.conf
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
