#!/usr/bin/env bash
# achieve passwordless SSH authentication using the private key ~/.ssh/school and to refuse authentication via password
Host 54.165.187.16
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
